import { Inter } from 'next/font/google'
import './globals.css'
import Cabecalho from '@/components/Cabecalho/cabecalho'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'M&M - Global Solution 02',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        
        <Cabecalho /> 
        {children}
        
        </body>
    </html>
  )
}
